"""
Digest generation service.

Runs a topic query through the LangGraph ReAct agent (search → synthesize),
formats the result as a clean HTML email, then delivers via SendGrid.
"""

import os
import re
from datetime import datetime, timezone

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from app.agent.core import run_task


# ─── HTML email template ─────────────────────────────────────────────────────

def _build_html(topic_name: str, summary: str, body: str, generated_at: str) -> str:
    """Wrap agent output in a clean, inline-styled HTML email."""
    # Convert markdown-style **bold** and bullet points to HTML
    body_html = body
    body_html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", body_html)
    body_html = body_html.replace("\n\n", "</p><p>").replace("\n", "<br>")
    body_html = f"<p>{body_html}</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

        <!-- Header -->
        <tr>
          <td style="background:#4f46e5;padding:28px 32px;">
            <p style="margin:0;color:#c7d2fe;font-size:12px;text-transform:uppercase;letter-spacing:1px;">AutoFlow Digest</p>
            <h1 style="margin:6px 0 0;color:#ffffff;font-size:22px;font-weight:700;">{topic_name}</h1>
          </td>
        </tr>

        <!-- TL;DR -->
        <tr>
          <td style="padding:24px 32px 0;">
            <div style="background:#f0f9ff;border-left:4px solid #4f46e5;padding:16px 20px;border-radius:0 8px 8px 0;">
              <p style="margin:0 0 4px;font-size:11px;font-weight:700;color:#4f46e5;text-transform:uppercase;letter-spacing:0.5px;">TL;DR</p>
              <p style="margin:0;color:#1e293b;font-size:14px;line-height:1.6;">{summary}</p>
            </div>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:24px 32px;color:#374151;font-size:15px;line-height:1.7;">
            {body_html}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:20px 32px;border-top:1px solid #f1f5f9;">
            <p style="margin:0;color:#94a3b8;font-size:12px;">
              Generated by <strong>AutoFlow</strong> · {generated_at}
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>"""


# ─── Core generation function ─────────────────────────────────────────────────

def generate_digest(topic_name: str, query: str) -> dict:
    """
    Run the search→synthesize agent loop and return structured digest content.

    Returns:
        {
            "subject": str,
            "html": str,
            "summary": str,
            "error": str | None
        }
    """
    agent_task = (
        f"Search for the latest information on: {query}\n\n"
        "Produce a digest with:\n"
        "1. A one-sentence TL;DR (label it 'TL;DR:')\n"
        "2. 3-5 key findings, each with a source URL where available\n"
        "3. A brief closing takeaway\n\n"
        "Be specific, factual, and concise. Cite sources inline."
    )

    result = run_task(agent_task, enabled_tools=["search", "summarize"])

    if result.status.value == "failed":
        return {"subject": "", "html": "", "summary": "", "error": result.error}

    content = result.result or ""

    # Extract TL;DR line if agent followed instructions
    summary = ""
    for line in content.splitlines():
        if line.lower().startswith("tl;dr"):
            summary = line.split(":", 1)[-1].strip()
            break
    if not summary:
        # Fall back to first sentence
        summary = content.split(".")[0].strip() + "."

    subject = f"{topic_name} Digest — {datetime.now(timezone.utc).strftime('%b %d, %Y')}"
    generated_at = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    html = _build_html(topic_name, summary, content, generated_at)

    return {"subject": subject, "html": html, "summary": summary, "error": None}


# ─── Email delivery ───────────────────────────────────────────────────────────

def send_digest_email(to_emails: list[str], subject: str, html: str) -> tuple[bool, str]:
    """
    Send the HTML digest via SendGrid.

    Returns (success: bool, message: str).
    """
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL")

    if not api_key or not from_email:
        return False, "SENDGRID_API_KEY or SENDGRID_FROM_EMAIL not set in .env"

    try:
        message = Mail(
            from_email=from_email,
            to_emails=to_emails,
            subject=subject,
            html_content=html,
        )
        client = SendGridAPIClient(api_key)
        response = client.send(message)
        return True, f"Delivered. Status: {response.status_code}"
    except Exception as e:
        return False, str(e)


# ─── Combined: generate + send ────────────────────────────────────────────────

def run_digest(topic_name: str, query: str, recipients: list[str]) -> dict:
    """
    Full pipeline: generate digest → send email → return result dict.

    Returns:
        {
            "subject": str,
            "html": str,
            "summary": str,
            "status": "sent" | "failed",
            "error": str | None,
            "sent_to": list[str]
        }
    """
    digest = generate_digest(topic_name, query)
    if digest["error"]:
        return {**digest, "status": "failed", "sent_to": []}

    success, msg = send_digest_email(recipients, digest["subject"], digest["html"])
    return {
        **digest,
        "status": "sent" if success else "failed",
        "error": None if success else msg,
        "sent_to": recipients if success else [],
    }
